server.port=9090

# Spring Profile
spring.profiles.active=dev

# Allow circular dependencies (use with caution)
spring.main.allow-circular-references=true

# Hibernate & JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.HANADialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.HANAColumnStoreDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# db
spring.datasource.url=jdbc:sap://e6f74ff4-6ada-4c8b-9bc5-d004f7aab6c5.hna1.prod-us10.hanacloud.ondemand.com:443?encrypt=true&validateCertificate=true&currentschema=COMPANY_HDI_COMPANY_DB_DEPLOYER_1
spring.datasource.username=COMPANY_HDI_COMPANY_DB_DEPLOYER_1_BB0G0GP3V4B5K06TR43STK64K_RT
spring.datasource.password=||O:]%57N+;.~%1DTEq<K3!e6R.V^6}x4s||Qm;L`qyr~O __!5K|kiFh31Tc*EMVE?(k~k#^dXJI;A;+8F%^^=RS2h%8EtYxt#fJr8Z!N4u?Uh<IuMB.74h}kS:&v_s

# Spring Security (Basic Auth)
spring.security.user.name=admin
spring.security.user.password=admin123